#!/bin/zsh

export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="alacritty"
export GIT_CONFIG_GLOBAL=$HOME/.config/git/config
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

if [ -d "$HOME/.local/bin" ]; then
    PATH=$PATH:"$HOME/.local/bin"
fi

if [ -d "$HOME/.dotnet/tools" ]; then
    PATH=$PATH:"$HOME/.dotnet/tools"
fi

if [ -d "$HOME/.cargo/bin" ]; then
    PATH=$PATH:"$HOME/.cargo/bin"
fi


export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gpg"
export GEM_HOME="$HOME/.local/share/gem"

# Microsoft telemetry opt-out
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# suggest history first, fallback to completion engine
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Add custom (spt) completions
# Initialize it using
# spt --completions zsh > $XDG_DATA_HOME/completions/_spt
export fpath=($XDG_DATA_HOME/completions/ $fpath)
