#!/bin/zsh

export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="ALACRITTY"
export GIT_CONFIG_GLOBAL=$HOME/.config/git/config
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"


export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gpg"

# Microsoft telemetry opt-out
export DOTNET_CLI_TELEMETRY_OPTOUT=1

