xinput set-prop 10 "libinput Tapping Enabled" 1
xinput set-prop 10 "libinput Natural Scrolling Enabled" 1
xset r rate 300 30

/usr/bin/lxpolkit &
eval "$(ssh-agent -s)"

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

# make keyring work
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

feh --bg-fill $HOME/Pictures/wallpapers/wallpaper.jpg

exec i3
