[window]

# padding.x = 0
# padding.y = 0

# decorations = "None"
# decorations_theme_variant = "Dark"

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 10.0

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"
